ALTER TABLE `recommendation_actions`
  MODIFY COLUMN `status` VARCHAR(20) NULL DEFAULT 'Pending',
  ADD COLUMN `recommendation_key` VARCHAR(191) NULL,
  ADD COLUMN `product_name` VARCHAR(100) NULL,
  ADD COLUMN `priority` VARCHAR(20) NULL,
  ADD COLUMN `title` VARCHAR(255) NULL,
  ADD COLUMN `description` TEXT NULL,
  ADD COLUMN `recommended_action` VARCHAR(100) NULL,
  ADD COLUMN `impact` VARCHAR(255) NULL,
  ADD COLUMN `generated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN `completed_at` TIMESTAMP NULL DEFAULT NULL,
  ADD COLUMN `action_history` TEXT NULL;
